services:
  db_postgres:
    container_name: CrewOpsDb
    build:
      context: .
      dockerfile: .docker/postgres.dockerfile
    environment:
      POSTGRES_DB: ${CREWOPS_POSTGRES_DB}
      POSTGRES_USER: ${CREWOPS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CREWOPS_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - crewOps
    volumes:
      - postgres_database:/var/lib/postgres/data

  core:
    container_name: CrewOpsCore
    build:
      context: .
      dockerfile: .docker/core.dockerfile
      pull: false
    env_file: .env-compose
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_postgres:5432/${CREWOPS_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${CREWOPS_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${CREWOPS_POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres
    restart: always
    networks:
      - crewOps

  vaadin:
    container_name: CrewOpsVaadin
    build:
      context: .
      dockerfile: .docker/vaadin.dockerfile
      pull: false
    env_file: .env-compose
    environment:
      CREWOPS_CLIENT_ID_INPUT: ${CREWOPS_CLIENT_ID_INPUT}
      JWT_CREWOPS: ${JWT_CREWOPS}
    ports:
      - "8081:8081"
    restart: always
    networks:
      - crewOps

networks:
  crewOps:

volumes:
  postgres_database: