package pl.crewops.view;

import com.vaadin.componentfactory.timeline.Timeline;
import com.vaadin.componentfactory.timeline.model.Item;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.router.BeforeEnterEvent;
import com.vaadin.flow.router.BeforeEnterObserver;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.List;
import pl.crewops.infrastructure.core.CoreAPI;
import pl.crewops.security.jwt.JwtServiceVaadin;
import pl.crewops.util.AuthenticationResolver;
import pl.crewops.view.layout.MainLayout;

@Route("daily")
@PageTitle("Daily Entry")
public class DailyView extends MainLayout implements BeforeEnterObserver {

    private static final int TIMELINE_WIDTH_PX = 2000;
    private static final double CONTAINER_WIDTH_PERCENT = 0.8; // 80%

    public DailyView(CoreAPI coreAPI, JwtServiceVaadin jwtService, AuthenticationResolver authenticationResolver) {
        super(coreAPI, jwtService, authenticationResolver);
    }

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        buildContent();
        //        if (authenticationResolver.principalIsAuthenticated()) {
        //            buildContent();
        //        } else {
        //            event.forwardTo(HomeView.class);
        //            UI.getCurrent().getPage().setLocation("/");
        //        }
    }

    private void buildContent() {
        Timeline timeline = getConfiguredTimeline();
        Div scrollContainer = getConfiguredScrollContainer(timeline);

        mainContent.add(scrollContainer);
    }

    /**
     * Oblicza, ile pikseli należy przesunąć scrollbar, aby aktualna godzina
     * była wyśrodkowana na widocznym obszarze.
     * * @return Pozycja scrolla w pikselach.
     */
    private int calculateScrollPosition() {
        LocalTime now = LocalTime.now();

        // 1. Całkowita długość dnia w sekundach (24 * 60 * 60)
        long totalDaySeconds = 24 * 60 * 60;

        // 2. Ilość sekund, która upłynęła od początku dnia
        long elapsedSeconds = now.toSecondOfDay();

        // 3. Procent ukończenia dnia (0.0 do 1.0)
        double progressRatio = (double) elapsedSeconds / totalDaySeconds;

        // 4. Pozycja aktualnej godziny na osi czasu (0 do 2000px)
        double currentPositionOnTimeline = progressRatio * TIMELINE_WIDTH_PX;

        // 5. Szerokość widocznego kontenera (przykładowo 80% z 1000px szerokości okna klienta)
        // Musimy oszacować tę szerokość, aby wyśrodkować wskaźnik.
        // Przyjmujemy, że wskaźnik ma być lekko na lewo, aby reszta dnia była widoczna.

        // Ustawiamy wskaźnik bieżącego czasu na 1/4 widocznego kontenera (bardziej widoczne będzie to, co przed nami)
        // Użyjemy stałej 250px jako przesunięcia w lewo (czyli 250px od lewej krawędzi kontenera)
        final int CENTER_OFFSET_PX = 250;

        // Ostateczna pozycja scrolla: Przesuwamy scrollbar tak, aby bieżąca godzina (currentPositionOnTimeline)
        // była oddalona o CENTER_OFFSET_PX od lewej krawędzi kontenera.
        int scrollPosition = (int) Math.round(currentPositionOnTimeline - CENTER_OFFSET_PX);

        if (scrollPosition < 0) {
            scrollPosition = 0;
        }

        final int MAX_SCROLL = TIMELINE_WIDTH_PX - 500;
        if (scrollPosition > MAX_SCROLL) {
            scrollPosition = MAX_SCROLL;
        }

        return scrollPosition;
    }

    /**
     * Auto scroll depends on actual time - logic generated by AI
     * */
    private Div getConfiguredScrollContainer(Timeline timeline) {
        Div scrollContainer = new Div(timeline);

        scrollContainer.setWidth("80%");
        scrollContainer.setHeight("140px");
        scrollContainer.getStyle().set("overflow-x", "auto");
        scrollContainer.getStyle().set("border", "1px solid #ccc");
        scrollContainer.getStyle().set("border-radius", "4px");
        scrollContainer.getStyle().set("padding", "5px");

        int scrollPosition = calculateScrollPosition();
        String jsCode = String.format("setTimeout(function() { $0.scrollLeft = %d; }, 100);", scrollPosition);
        UI.getCurrent().getPage().executeJs(jsCode, scrollContainer.getElement());

        return scrollContainer;
    }

    private Timeline getConfiguredTimeline() {
        List<Item> items = createTimelineItems();

        Timeline timeline = new Timeline(items);

        LocalDate today = LocalDate.now();
        timeline.setTimelineRange(LocalDateTime.of(today, LocalTime.MIN), LocalDateTime.of(today, LocalTime.MAX));

        timeline.setHeight("120px");
        timeline.setMoveable(true);
        timeline.setShowCurentTime(true);
        timeline.setZoomable(false);
        timeline.setWidth(TIMELINE_WIDTH_PX + "px");

        return timeline;
    }

    private List<Item> createTimelineItems() {

        LocalDate staticDay = LocalDate.of(2021, 8, 12);

        Item item1 = new Item(
                LocalDateTime.of(2021, 8, 11, 2, 30, 00),
                LocalDateTime.of(2021, 8, 11, 8, 00, 00),
                "Item 1 - Praca na projekcie A");
        item1.setId("1");

        Item item2 = new Item(
                LocalDateTime.of(2021, 8, 11, 9, 00, 00),
                LocalDateTime.of(2021, 8, 11, 17, 00, 00),
                "Item 2 - Spotkanie z klientem");
        item2.setId("2");

        Item item3 = new Item(staticDay.atTime(0, 30, 00), staticDay.atTime(3, 0, 00), "Item 3 - Migracja serwera");
        item3.setId("3");

        Item item4 = new Item(staticDay.atTime(4, 30, 00), staticDay.atTime(20, 0, 00), "Item 4 - Dzień wolny");
        item4.setId("4");

        Item item5 =
                new Item(staticDay.atTime(21, 30, 00), staticDay.plusDays(1).atTime(1, 15, 00), "Item 5 - Wdrożenie");
        item5.setId("5");

        List<Item> items = Arrays.asList(item1, item2, item3, item4, item5);

        items.forEach(i -> {
            i.setEditable(true);
            i.setUpdateTime(true);
        });

        return items;
    }
}
