spring:
  application:
    name: CrewOps Core

  profiles:
    default: dev

  config:
    import:
      - classpath:application-liquibase.yaml
      - classpath:application-email-config.yaml

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  mail:
    host: email-smtp.eu-west-1.amazonaws.com
    port: 587
    #    username: ${CREWOPS_EMAIL_LOGIN}
    username: AKIA6EFCBU7LKMYPDLTN
    #    password: ${CREWOPS_EMAIL_PASSWORD}
    password: BP/dL/KMXJvIAeJXSW+0hElpnXEGZIVbOubTnRxVz16N
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true

security:
  properties:
    clientId: ${CREWOPS_CLIENT_ID_HASH}
    clientIdInput: ${CREWOPS_CLIENT_ID_INPUT}
    jwtSecret: ${JWT_CREWOPS}
    jwtExpiration: ${JWT_EXPIRATION_CREWOPS}