  spring:
    application:
      name: CrewOps UI

    profiles:
      active: dev

    cache:
      cache-names: employeeCache

  security:
    properties:
      clientIdInput: ${CREWOPS_CLIENT_ID_INPUT}