server:
  port: 8081

spring:
  application:
    name: CrewOps UI

  profiles:
    active: dev

  cache:
    cache-names: getAllEmployees, getAllQualifications, getCompanyById, getEmployeeById
    redis:
      time-to-live: 3600000

security:
  properties:
    clientIdInput: ${CREWOPS_CLIENT_ID_INPUT}

core:
  base-url: http://crewops-service-be:8080