databaseChangeLog:
  - changeSet:
      id: 001-create-schema
      author: jkuznik
      changes:
        - sql:
            sql: "CREATE SCHEMA IF NOT EXISTS ${tenant.schema.name};"

  - changeSet:
      id: 002-set-search-path
      author: jkuznik
      changes:
        - sql:
            sql: "SET search_path TO ${tenant.schema.name};"

  - include:
      file: db/changelog/db.changelog-tenant.yaml

  - changeSet:
      id: 003-insert-admin-account-values
      author: jkuznik
      changes:
        - insert:
            tableName: address
            columns:
              - column:
                  name: id
                  value: ${address.id}
              - column:
                  name: version
                  valueNumeric: 0
              - column:
                  name: postal_code
                  value: ${address.postal.code}
              - column:
                  name: city
                  value: ${address.city}
              - column:
                  name: street
                  value: ${address.street}
              - column:
                  name: local_number
                  value: ${address.local.number}
              - column:
                  name: created_at
                  valueComputed: "CURRENT_TIMESTAMP"
              - column:
                  name: updated_at
                  valueComputed: "CURRENT_TIMESTAMP"

        - insert:
            tableName: company
            columns:
              - column:
                  name: id
                  value: ${company.id}
              - column:
                  name: version
                  valueNumeric: 0
              - column:
                  name: name
                  value: ${company.name}
              - column:
                  name: address_id
                  value: ${company.address.id}
              - column:
                  name: email
                  value: ${company.email}
              - column:
                  name: status
                  value: ${company.status}
              - column:
                  name: created_at
                  valueComputed: "CURRENT_TIMESTAMP"
              - column:
                  name: updated_at
                  valueComputed: "CURRENT_TIMESTAMP"

        - insert:
            tableName: employee
            columns:
              - column:
                  name: id
                  value: ${employee.id}
              - column:
                  name: version
                  valueNumeric: 0
              - column:
                  name: first_name
                  value: ${employee.first.name}
              - column:
                  name: last_name
                  value: ${employee.last.name}
              - column:
                  name: birth_date
                  value: ${employee.birth.date}
              - column:
                  name: phone_number
                  value: ${employee.phone.number}
              - column:
                  name: department
                  value: admin
              - column:
                  name: active
                  value: true
              - column:
                  name: created_at
                  valueComputed: "CURRENT_TIMESTAMP"
              - column:
                  name: updated_at
                  valueComputed: "CURRENT_TIMESTAMP"

  - changeSet:
      id: 004-reset-search-path
      author: jkuznik
      changes:
        - sql:
            sql: "SET search_path TO public;"