databaseChangeLog:
  - changeSet:
      id: 001-insert-admin-account-values
      author: jkuznik
      changes:
        - insert:
            tableName: address
            columns:
              - column: { name: id, value: "8faf1d5c-9e8f-4bca-9c56-123456789aab" }
              - column: { name: version, value: 0 }
              - column: { name: postal_code, value: "postalCode" }
              - column: { name: city, value: "city" }
              - column: { name: street, value: "street" }
              - column: { name: local_number, value: "localNumber" }
              - column: { name: created_at, valueComputed: "CURRENT_TIMESTAMP" }
              - column: { name: updated_at, valueComputed: "CURRENT_TIMESTAMP" }

        - insert:
            tableName: company
            columns:
              - column: { name: id, value: "2b3b7d5c-9e8f-4bca-9c56-123456789abd" }
              - column: { name: version, value: 0 }
              - column: { name: name, value: "CrewOps" }
              - column: { name: address_id, value: "8faf1d5c-9e8f-4bca-9c56-123456789aab" }
              - column: { name: email, value: "disaster.alert2@gmail.com" }
              - column: { name: status, value: "ACTIVE" }
              - column: { name: created_at, valueComputed: "CURRENT_TIMESTAMP" }
              - column: { name: updated_at, valueComputed: "CURRENT_TIMESTAMP" }

        - insert:
            tableName: employee
            columns:
              - column: { name: id, value: "1cd62a5c-9e2f-4bca-9c56-123456789abc" }
              - column: { name: version, value: 0 }
              - column: { name: first_name, value: "Admin" }
              - column: { name: last_name, value: "User" }
              - column: { name: birth_date, value: "2000-01-01" }
              - column: { name: phone_number, value: "123456789" }
              - column: { name: department, value: "Administration" }
              - column: { name: created_at, valueComputed: "CURRENT_TIMESTAMP" }
              - column: { name: updated_at, valueComputed: "CURRENT_TIMESTAMP" }