package pl.crewops.domain.dailyEntry;

import static pl.crewops.domain.dailyEntry.DailyEntryMapper.mapToDTO;
import static pl.crewops.domain.dailyEntry.DailyEntryMapper.mapToEntity;

import com.fasterxml.jackson.databind.JsonNode;
import java.time.LocalDate;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import pl.crewops.enums.DailyEntryAuditType;
import pl.crewops.exception.domain.dailyEntry.DailyEntryNotFoundException;
import pl.crewops.model.dto.dailyEntry.CreateDailyEntryDTO;
import pl.crewops.model.dto.dailyEntry.DailyEntryDTO;
import pl.crewops.model.tenantSchema.DailyEntry;
import pl.crewops.model.tenantSchema.DailyEntryAudit;
import pl.crewops.util.audit.AuditDetailsBuilder;

@Slf4j
@Component
@RequiredArgsConstructor
class DailyEntryService implements DailyEntryAPI {

    private static final String INITIAL_COMMENT = "Initial event with status: ";

    private final DailyEntryRepository dailyEntryRepository;
    private final DailyEntryAuditRepository dailyEntryAuditRepository;
    private final AuditDetailsBuilder auditDetailsBuilder;

    @Override
    @Transactional
    public DailyEntryDTO createDailyEntryManually(CreateDailyEntryDTO createDailyEntryDTO) {
        DailyEntry dailyEntry = mapToEntity(createDailyEntryDTO);

        DailyEntry savedEntry = dailyEntryRepository.save(dailyEntry);

        JsonNode payloadNode =
                auditDetailsBuilder.createPayload(DailyEntryAuditType.ENTRY_STATUS_CHANGED, null, savedEntry);

        DailyEntryAudit auditEvent = DailyEntryAudit.builder()
                .dailyEntry(savedEntry)
                .actionByEmployeeId(createDailyEntryDTO.actionByEmployeeId())
                .eventType(DailyEntryAuditType.ENTRY_STATUS_CHANGED)
                .payload(payloadNode)
                .comment(INITIAL_COMMENT + savedEntry.getStatus())
                .build();

        dailyEntryAuditRepository.save(auditEvent);

        return mapToDTO(savedEntry);
    }

    @Override
    @Transactional
    public DailyEntryDTO autoGenerateDailyEntry(CreateDailyEntryDTO createDailyEntryDTO) {
        // Logika automatycznego generowania wpisu
        DailyEntry dailyEntry = mapToEntity(createDailyEntryDTO);
        DailyEntry savedEntry = dailyEntryRepository.save(dailyEntry);

        // Tworzymy payload dla całego rekordu
        JsonNode payloadNode = auditDetailsBuilder.createPayload(
                DailyEntryAuditType.ATTENDANCE_STATUS_CHANGED, // lub inny typ zależnie od logiki
                null,
                savedEntry);

        DailyEntryAudit auditEvent = DailyEntryAudit.builder()
                .dailyEntry(savedEntry)
                .actionByEmployeeId(createDailyEntryDTO.actionByEmployeeId())
                .eventType(DailyEntryAuditType.ATTENDANCE_STATUS_CHANGED)
                .payload(payloadNode)
                .comment("Auto-generated entry")
                .build();

        dailyEntryAuditRepository.save(auditEvent);

        return mapToDTO(savedEntry);
    }

    @Override
    @Transactional(readOnly = true)
    public DailyEntryDTO getByEmployeeIdAndEntryDate(UUID employeeId, LocalDate entryDate) {
        DailyEntry dailyEntry = dailyEntryRepository
                .findByEmployeeIdAndEntryDate(employeeId, entryDate)
                .orElseThrow(() -> new DailyEntryNotFoundException(employeeId, entryDate));

        return mapToDTO(dailyEntry);
    }
}
