package pl.crewops.domain.dailyEntry;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import java.util.UUID;
import org.springframework.validation.annotation.Validated;
import pl.crewops.model.dto.dailyEntry.CreateDailyEntryDTO;
import pl.crewops.model.dto.dailyEntry.DailyEntryDTO;
import pl.crewops.model.dto.dailyEntry.UpdateDailyEntryCommand;
import pl.crewops.model.tenantSchema.DailyEntry;

@Validated
public interface DailyEntryAPI {

    DailyEntryDTO createDailyEntryManually(@NotNull @Valid CreateDailyEntryDTO createDailyEntryDTO);

    DailyEntryDTO autoGenerateDailyEntry(@NotNull @Valid CreateDailyEntryDTO createDailyEntryDTO);

    DailyEntry getById(@NotNull @Valid UUID id);

    DailyEntryDTO getByEmployeeIdAndEntryDate(@NotNull UUID employeeId, @NotNull LocalDate entryDate);

    DailyEntryDTO updateDailyEntry(@NotNull @Valid UpdateDailyEntryCommand updateAttendance);

    DailyEntryDTO approveDailyEntry(@NotNull @Valid UpdateDailyEntryCommand updateDailyEntryCommand);
}
