package pl.crewops.domain.dailyEntry;

import static pl.crewops.domain.dailyEntry.DailyEntryMapper.mapToDTO;
import static pl.crewops.domain.dailyEntry.DailyEntryMapper.mapToEntity;

import com.fasterxml.jackson.databind.JsonNode;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import pl.crewops.enums.DailyEntryAuditType;
import pl.crewops.enums.DailyEntryStatus;
import pl.crewops.exception.domain.dailyEntry.DailyEntryNotFoundException;
import pl.crewops.model.dto.dailyEntry.CreateDailyEntryDTO;
import pl.crewops.model.dto.dailyEntry.DailyEntryDTO;
import pl.crewops.model.dto.dailyEntry.UpdateDailyEntryCommand;
import pl.crewops.model.tenantSchema.DailyEntry;
import pl.crewops.model.tenantSchema.DailyEntryAudit;
import pl.crewops.util.audit.AuditDetailsBuilder;

@Slf4j
@Component
@RequiredArgsConstructor
class DailyEntryService implements DailyEntryAPI {

    private static final String INITIAL_COMMENT = "Initial status set to: ";

    private final DailyEntryRepository dailyEntryRepository;
    private final DailyEntryAuditRepository dailyEntryAuditRepository;
    private final AuditDetailsBuilder auditDetailsBuilder;

    @Override
    @Transactional
    public DailyEntryDTO createDailyEntryManually(CreateDailyEntryDTO createDailyEntryDTO) {

        final DailyEntry dailyEntry = mapToEntity(createDailyEntryDTO);

        final DailyEntry savedEntry = dailyEntryRepository.save(dailyEntry);

        final JsonNode payloadNode = auditDetailsBuilder.createPayload(
                DailyEntryAuditType.ENTRY_STATUS_CHANGED, null, savedEntry, createDailyEntryDTO.actionByEmployeeId());

        final DailyEntryAudit auditEvent = DailyEntryAudit.builder()
                .dailyEntry(savedEntry)
                .actionByEmployeeId(createDailyEntryDTO.actionByEmployeeId())
                .eventType(DailyEntryAuditType.ENTRY_STATUS_CHANGED)
                .payload(payloadNode)
                .comment(INITIAL_COMMENT + savedEntry.getStatus())
                .build();

        dailyEntryAuditRepository.save(auditEvent);

        return mapToDTO(savedEntry);
    }

    @Override
    @Transactional
    public DailyEntryDTO autoGenerateDailyEntry(CreateDailyEntryDTO createDailyEntryDTO) {
        // Logika automatycznego generowania wpisu
        DailyEntry dailyEntry = mapToEntity(createDailyEntryDTO);
        DailyEntry savedEntry = dailyEntryRepository.save(dailyEntry);

        //        // Tworzymy payload dla całego rekordu
        //        JsonNode payloadNode = auditDetailsBuilder.createPayload(
        //                DailyEntryAuditType.ATTENDANCE_STATUS_CHANGED, // lub inny typ zależnie od logiki
        //                null,
        //                savedEntry);

        DailyEntryAudit auditEvent = DailyEntryAudit.builder()
                .dailyEntry(savedEntry)
                .actionByEmployeeId(createDailyEntryDTO.actionByEmployeeId())
                .eventType(DailyEntryAuditType.ATTENDANCE_STATUS_CHANGED)
                //                .payload(payloadNode)
                .comment("Auto-generated entry")
                .build();

        dailyEntryAuditRepository.save(auditEvent);

        return mapToDTO(savedEntry);
    }

    @Override
    @Transactional(readOnly = true)
    public DailyEntryDTO getByEmployeeIdAndEntryDate(UUID employeeId, LocalDate entryDate) {
        DailyEntry dailyEntry = dailyEntryRepository
                .findByEmployeeIdAndEntryDate(employeeId, entryDate)
                .orElseThrow(() -> new DailyEntryNotFoundException(employeeId, entryDate));

        return mapToDTO(dailyEntry);
    }

    @Transactional
    public DailyEntryDTO updateDailyEntry(UpdateDailyEntryCommand command) {
        DailyEntry dailyEntry = dailyEntryRepository
                .findByEmployeeIdAndEntryDate(command.employeeId(), command.entryDate())
                .orElseThrow(() -> new DailyEntryNotFoundException(command.employeeId(), command.entryDate()));

        DailyEntry oldEntry = cloneDailyEntry(dailyEntry);
        DailyEntryAuditType auditType;

        switch (command) {
            case UpdateDailyEntryCommand.UpdateAttendance update -> {
                dailyEntry.setAttendance(update.newAttendance());
                auditType = DailyEntryAuditType.ATTENDANCE_STATUS_CHANGED;
            }
            case UpdateDailyEntryCommand.UpdateWorkTime update -> {
                dailyEntry.setStartTime(update.newStartTime());
                dailyEntry.setEndTime(update.newEndTime());
                dailyEntry.setOvertime(update.newOvertime());
                auditType = DailyEntryAuditType.WORK_TIME_MODIFIED;
            }
            case UpdateDailyEntryCommand.ChangeEntryStatus update -> {
                dailyEntry.setStatus(update.newStatus());
                auditType = DailyEntryAuditType.ENTRY_STATUS_CHANGED;
            }
            case UpdateDailyEntryCommand.AddDailyNote update -> {
                // TODO: implement note persistence logic
                auditType = DailyEntryAuditType.DAILY_NOTE_ADDED;
            }
        }

        DailyEntry savedEntry = dailyEntryRepository.save(dailyEntry);

        // Główne zdarzenie audytowe (np. WORK_TIME_MODIFIED)
        JsonNode payloadNode =
                auditDetailsBuilder.createPayload(auditType, oldEntry, savedEntry, command.actionByEmployeeId());

        dailyEntryAuditRepository.save(DailyEntryAudit.builder()
                .dailyEntry(savedEntry)
                .actionByEmployeeId(command.actionByEmployeeId())
                .eventType(auditType)
                .payload(payloadNode)
                .comment(command.comment())
                .build());

        if (oldEntry.getStatus() == DailyEntryStatus.APPROVED && sensitiveModification(oldEntry, savedEntry)) {

            DailyEntryStatus previousStatus = savedEntry.getStatus();
            savedEntry.setStatus(DailyEntryStatus.MANUAL_EDITED);
            dailyEntryRepository.save(savedEntry);

            // osobny event audytowy: cofnięcie zatwierdzenia
            JsonNode statusChangePayload = auditDetailsBuilder.createPayload(
                    DailyEntryAuditType.ENTRY_STATUS_CHANGED, oldEntry, savedEntry, command.actionByEmployeeId());

            DailyEntryAudit entryStatusChangedAudit = DailyEntryAudit.builder()
                    .dailyEntry(savedEntry)
                    .actionByEmployeeId(command.actionByEmployeeId())
                    .eventType(DailyEntryAuditType.ENTRY_STATUS_CHANGED)
                    .payload(statusChangePayload)
                    .comment("Entry was modified after approval — status reverted to MANUAL_EDITED")
                    .build();

            dailyEntryAuditRepository.save(entryStatusChangedAudit);
        }

        return mapToDTO(savedEntry);
    }

    /**
     * Determines whether the modification of a DailyEntry affects core ("sensitive") fields.
     * <p>
     * A "sensitive modification" is one that should trigger a status change
     * from APPROVED → MANUAL_EDITED. These include:
     * <ul>
     *   <li>Change of attendance status</li>
     *   <li>Change of start time</li>
     *   <li>Change of end time</li>
     *   <li>Change of overtime</li>
     * </ul>
     *
     * @param oldEntry the original DailyEntry state (before update)
     * @param newEntry the updated DailyEntry state (after update)
     * @return {@code true} if a sensitive modification occurred, otherwise {@code false}
     */
    boolean sensitiveModification(DailyEntry oldEntry, DailyEntry newEntry) {

        // Check attendance change
        if (!Objects.equals(oldEntry.getAttendance(), newEntry.getAttendance())) {
            return true;
        }

        // Check work time changes
        if (!Objects.equals(oldEntry.getStartTime(), newEntry.getStartTime())) {
            return true;
        }
        if (!Objects.equals(oldEntry.getEndTime(), newEntry.getEndTime())) {
            return true;
        }

        // Check overtime changes (handle null and numeric equality properly)
        if (!Objects.equals(
                Optional.ofNullable(oldEntry.getOvertime())
                        .map(BigDecimal::stripTrailingZeros)
                        .orElse(null),
                Optional.ofNullable(newEntry.getOvertime())
                        .map(BigDecimal::stripTrailingZeros)
                        .orElse(null))) {
            return true;
        }

        // Other modifications (notes, comments, etc.) do NOT trigger status change
        return false;
    }

    private DailyEntry cloneDailyEntry(DailyEntry source) {
        var dailyEntry = DailyEntry.builder()
                .employeeId(source.getEmployeeId())
                .entryDate(source.getEntryDate())
                .attendance(source.getAttendance())
                .status(source.getStatus())
                .startTime(source.getStartTime())
                .endTime(source.getEndTime())
                .overtime(source.getOvertime())
                .build();
        dailyEntry.setId(source.getId());
        return dailyEntry;
    }
}
