name: Run crewops-core on host

on:
  workflow_run:
    workflows: ["Build & Push core image"]
    types:
      - completed

jobs:
  deploy-core:
    runs-on: [self-hosted, linux]

    steps:
      - name: Pull latest image
        run: sudo docker pull jkuznik/crewops-core:latest

      - name: Remove old container (if exists)
        run: sudo docker rm -f core || true

      - name: Run new container
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          CREWOPS_CLIENT_ID_HASH: ${{ secrets.CREWOPS_CLIENT_ID_HASH }}
          CREWOPS_CLIENT_ID_INPUT: ${{ secrets.CREWOPS_CLIENT_ID_INPUT }}
          JWT_CREWOPS: ${{ secrets.JWT_CREWOPS }}
          JWT_EXPIRATION_CREWOPS: ${{ secrets.JWT_EXPIRATION_CREWOPS }}
        run: |
          sudo docker run -d \
            --name core \
            --network crewOps \
            -e SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL \
            -e SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME \
            -e SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD \
            -e CREWOPS_CLIENT_ID_HASH=$CREWOPS_CLIENT_ID_HASH \
            -e CREWOPS_CLIENT_ID_INPUT=$CREWOPS_CLIENT_ID_INPUT \
            -e JWT_CREWOPS=$JWT_CREWOPS \
            -e JWT_EXPIRATION_CREWOPS=$JWT_EXPIRATION_CREWOPS \
            -e TZ=Europe/Warsaw \
            -p 8080:8080 \
            --memory=300m \
            jkuznik/crewops-core:latest
