#name: Build And Push core image
#
#on:
#  push:
#    branches: [ "main" ]
#    paths:
#      - 'CrewOpsCore/**'
#      - '.docker/core.dockerfile'
#      - 'settings.gradle.kts'
#      - 'build.gradle.kts'
#      - 'gradle/**'
#      - '.github/workflows/**'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Docker login
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#
#      - name: Build core image
#        run: |
#          docker build -t jkuznik/crewops-core:${{ github.sha }} -f $GITHUB_WORKSPACE/.docker/core.dockerfile $GITHUB_WORKSPACE
#          docker tag jkuznik/crewops-core:${{ github.sha }} jkuznik/crewops-core:latest
#
#      - name: Push core image
#        run: |
#          docker push jkuznik/crewops-core:${{ github.sha }}
#          docker push jkuznik/crewops-core:latest
#
##          # ✅ Install AWS PowerShell and login to ECR
##      - name: Install AWS CLI v2
##        run: |
##          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
##          unzip -u awscliv2.zip
##          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
##          aws --version
##
##      - name: Configure AWS CLI for ECR
##        run: |
##          aws configure set aws_access_key_id ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
##          aws configure set aws_secret_access_key ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
##          aws configure set region ${{ secrets.AWS_REGION }}
##
##      - name: Push Docker image to ECR
##        run: |
##          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
##          REPO_URI="$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jkuznik-ecr/crewops-core"
##
##          docker tag jkuznik/crewops-core:${{ github.sha }} $REPO_URI:${{ github.sha }}
##          docker tag jkuznik/crewops-core:${{ github.sha }} $REPO_URI:latest
##
##          aws ecr get-login-password | docker login --username AWS --password-stdin $REPO_URI
##          docker push $REPO_URI:${{ github.sha }}
##          docker push $REPO_URI:latest
#
#
