name: Run application on host

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Update docker image"]
    types:
      - completed

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Pull docker image
        run: sudo docker pull jkuznik/crewops:latest
      - name: Delete old docker container
        run: sudo docker rm -f crewops-container || true
      - name: Run new docker container
        env:
          TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
          TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
          TWILIO_PHONE_NUMBER: ${{secrets.TWILIO_PHONE_NUMBER}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
          DAY_SMS_LIMIT: ${{secrets.DAY_SMS_LIMIT}}
          RISK_THRESHOLD: ${{secrets.RISK_THRESHOLD}}
        run: |
          sudo docker run -d --name crewops-container --network crewOps -p 8080:8080 jkuznik/crewops