name: Run Vaadin container on host

on:
  workflow_run:
    workflows: ["Build And Push vaadin image"]
    types:
      - completed

jobs:
  deploy-vaadin:
    runs-on: [self-hosted, linux]

    steps:
      - name: Pull latest Vaadin image
        run: sudo docker pull jkuznik/crewops-vaadin:latest

      - name: Remove old Vaadin container
        run: sudo docker rm -f CrewOpsVaadin || true

      - name: Run new Vaadin container
        env:
          CREWOPS_CLIENT_ID_INPUT: ${{ secrets.CREWOPS_CLIENT_ID_INPUT }}
          CREWOPS_CLIENT_ID_HASH: ${{ secrets.CREWOPS_CLIENT_ID_HASH }}
          JWT_CREWOPS: ${{ secrets.JWT_CREWOPS }}
          JWT_EXPIRATION_CREWOPS: ${{ secrets.JWT_EXPIRATION_CREWOPS }}
        run: |
          sudo docker run -d \
            --name CrewOpsVaadin \
            --network crewOps \
            --restart always \
            -e CREWOPS_CLIENT_ID_INPUT=$CREWOPS_CLIENT_ID_INPUT \
            -e CREWOPS_CLIENT_ID_HASH=$CREWOPS_CLIENT_ID_HASH \
            -e JWT_CREWOPS=$JWT_CREWOPS \
            -e JWT_EXPIRATION_CREWOPS=$JWT_EXPIRATION_CREWOPS \
            -e TZ=Europe/Warsaw \
            -p 8081:8081 \
            --memory=512m \
            jkuznik/crewops-vaadin:latest

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -u awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          aws --version

      - name: Configure AWS CLI for ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Push Docker image to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REPO_URI="$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jkuznik-ecr/crewops-vaadin"

          docker tag jkuznik/crewops-vaadin:${{ github.sha }} $REPO_URI:${{ github.sha }}
          docker tag jkuznik/crewops-vaadin:${{ github.sha }} $REPO_URI:latest

          aws ecr get-login-password | docker login --username AWS --password-stdin $REPO_URI
          docker push $REPO_URI:${{ github.sha }}
          docker push $REPO_URI:latest